### ISSUE TITLE
Null pointer exception with REAMDE example

### ISSUE THREAD

**Issue by DBarthe** [gaul/s3proxy#254] opened 2018-01-15 17:29 UTC
Hello,

While testing s3proxy with the example given in the README, I got a NullPointerException.

s3Proxy.conf:
```
s3proxy.authorization=none
s3proxy.endpoint=http://127.0.0.1:7777
jclouds.provider=filesystem
jclouds.filesystem.basedir=/tmp/s3proxy
```

Any command like `curl http://127.0.0.1:7777` returns an error:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /. Reason:
<pre>    java.lang.NullPointerException</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

And a stacktrace;
```
java.lang.NullPointerException: null
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:400)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
```

When I plugged with a java debugger :

![image](https://user-images.githubusercontent.com/5542307/34954570-31f30562-fa21-11e7-90ee-abe13e733dbf.png)

Do I missed something ?

**Comment by gaul** [comment] 2018-01-15 18:05
Duplicate of #251.  Do you use 1.5.4?  I will release 1.5.5 this week containing a fix for this issue.  In the mean-time you can use 1.5.3 or 1.6.0-SNAPSHOT.

**Closed by gaul** 2018-01-15 18:05 UTC

**Comment by DBarthe** [comment] 2018-01-16 14:51
Okay thank you :)
