### ISSUE TITLE
Connecting to Azure Managed Identity using S3proxy

### ISSUE THREAD

**Issue by AkkiSawant** [gaul/s3proxy#588] opened 2024-01-04 08:53 UTC
We are using s3proxy and trying to connect to Azure managed identity using the same but we are getting connection issues

We used "jclouds.azureblob.auth" jcloud setting too but it has support for AzureAd and AzureKey

We are making use of AZURE_CLIENT_ID instead of the usual azure access key, do we have to configure / set any other config or settings in s3proxy or jclouds to establish connection using managed identity ?

Has anyone tried to connect to Azure managed identity using s3proxy ? Does it provides the  support for managed identity ?

**Comment by gaul** [comment] 2024-02-20 02:20
Duplicate of #580.

**Closed by gaul** 2024-02-20 02:20 UTC
