### ISSUE TITLE
Azure Managed Identity support in S3 proxy

### ISSUE THREAD

**Issue by apoorva-dapake-bh** [gaul/s3proxy#580] opened 2023-12-12 05:22 UTC
Does s3Proxy support managed identity to connect to azure container?

**Comment by apoorva-dapake-bh** [comment] 2023-12-20 11:33
There is setting with jcloud 'jclouds.azureblob.auth' to support different Auth methods such as AzureAd and AzureKey.
Is there any setting for managed identity?

**Comment by pegasas** [comment] 2024-01-09 12:07
here's some introduction about https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/tutorial-linux-vm-access-storage.
looks like it it wait for implementation

**Comment by gaul** [comment] 2024-02-20 02:24
Duplicate of #536.

**Closed by gaul** 2024-02-20 02:24 UTC
