### ISSUE TITLE
ListObjects performs un-needed recursive listing on bucket with filesystem provider

### ISSUE THREAD

**Issue by juangburgos** [gaul/s3proxy#575] opened 2023-11-16 17:48 UTC
Awesome software, just one detail:

When there is a ListObjects request with a `/` delimeter, the filesystem provider should only query the folders, instead it does a recursive listing of all the sub-tree in the bucket (filesystem folder) which is un-needed and very expensive for deep trees with lots of files.

Basically in the logs we see one entry per file in the subtree recursivelly!:
```
[s3proxy] D [timestamp] S3Proxy-Jetty-40 o.j.b.config.LocalBlobStore:56 |::] Opening blob in container: [file]
```
Of course any S3 client timesout when the sub-tree is large.

**Comment by gaul** [comment] 2023-11-17 04:06
Duplicate of #473.  You can work around this by setting `jclouds.version` to 2.6.0-SNAPSHOT.

**Closed by gaul** 2023-11-17 04:06 UTC

**Comment by juangburgos** [comment] 2023-11-17 08:27
Sorry, did not know it was a dupe, not knowledgeable in Java, how/where would I change this parameter? I guess in `s3proxy.conf`? I will try tonight. Thanks!

**Comment by gaul** [comment] 2023-11-17 12:45
You need to edit `pom.xml` and compile S3Proxy with `mvn package`.

**Comment by juangburgos** [comment] 2023-11-17 17:56
Thanks, that worked, tests are fialing though, had to run with:
```
mvn package -DskipTests
```
 Now is fast for only querying the folders, but now the folder names are returned with the trailing `\` which s3 clients will subsequently use and now querying the subfolder is failing, I suspect is due to that trailing `\`.

**Comment by juangburgos** [comment] 2023-11-17 23:49
Now the problem is on Windows, the returned sub-folders have the trailing `\`, for example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>converted</Name>
  <Prefix/>
  <KeyCount>2</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <ContinuationToken/>
  <StartAfter/>
  <Delimiter>/</Delimiter>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>some-file.txt</Key>
    <LastModified>2020-05-01T23:37:35Z</LastModified>
    <Size>693</Size>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <CommonPrefixes>
    <Prefix>some-folder\</Prefix>
  </CommonPrefixes>
</ListBucketResult>
```
Which then an S3 client wil try to use to query the subfolder, and everything breaks from then on.

**Comment by juangburgos** [comment] 2023-11-18 00:10
I have managed to make it work by adding the following to my reverse proxy configuration:
```
AddOutputFilterByType SUBSTITUTE application/xml
Substitute "s|\|/|n"
```
Basically substitute `\` for `/` for XML responses. And now is usable 👍
