### ISSUE TITLE
Usage without Docker broken in 1.5.4

### ISSUE THREAD

**Issue by damselem** [gaul/s3proxy#253] opened 2018-01-08 12:46 UTC
Tested with 1.5.3 and it worked, but seems to be broken with 1.5.4.

s3proxy.conf
=========
s3proxy.authorization=none
s3proxy.endpoint=http://127.0.0.1:8080
jclouds.provider=filesystem
jclouds.filesystem.basedir=/tmp/s3proxy

server
=====
$ target/s3proxy --properties ../s3proxy.conf
[s3proxy] I 01-08 14:44:14.367 main org.eclipse.jetty.util.log:186 |::] Logging initialized @1061ms
[s3proxy] I 01-08 14:44:14.404 main o.eclipse.jetty.server.Server:327 |::] jetty-9.2.z-SNAPSHOT
[s3proxy] I 01-08 14:44:14.458 main o.e.j.server.ServerConnector:266 |::] Started ServerConnector@42b02722{HTTP/1.1}{127.0.0.1:8080}
[s3proxy] I 01-08 14:44:14.458 main o.eclipse.jetty.server.Server:379 |::] Started @1155ms
[s3proxy] W 01-08 14:44:17.850 S3Proxy-Jetty-18 o.e.jetty.server.HttpChannel:396 |::] /
java.lang.NullPointerException: null
        at org.gaul.s3proxy.S3ProxyHandler.doHandle(S3ProxyHandler.java:400)
        at org.gaul.s3proxy.S3ProxyHandlerJetty.handle(S3ProxyHandlerJetty.java:70)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

client
====
$ curl http://localhost:8080/

**Comment by gaul** [comment] 2018-01-08 23:32
Duplicate of #251.

**Closed by gaul** 2018-01-08 23:32 UTC

**Comment by gaul** [comment] 2018-01-09 06:57
Fixed by 0f26d6584638602bc74a1b39cc7993a69e7cc2af.
