### ISSUE TITLE
Not able to connect to azure blobstore using using managed-identities using S3 Proxy.

### ISSUE THREAD

**Issue by anurag-prasad-bh** [gaul/s3proxy#548] opened 2023-08-25 05:30 UTC
Hi Team,
  Our application is not able to connect to azure store using managed identities using S3Proxy.
I tried to use the below configuration 
jclouds.azureblob.auth=azureAd
jclouds.azureblob.tenantId=<tenant ID>
jclouds.azureblob.account=<Azure Blob storage account>
AZureIdentity and Credentials is a manadatory field.As we are trying to connect to azure storage by passing an empty value as our assumption was we should be able to connctb to azure storage without providing credentials.I am getting the below error.
{
    "status": 500,
    "name": "INTERNAL_SERVER_ERROR",
    "message": "Exception occurred at Azure server ",
    "details": "Forbidden (Service: S3, Status Code: 403, Request ID: 4442587FB7D0A2F9)"
}

**Comment by anurag-prasad-bh** [comment] 2023-08-25 06:02
Also if you can you send me the configuration details for S3Proxy to connect to azure blobstore using managed identity

**Comment by gaul** [comment] 2024-02-20 02:24
Duplicate of #536.

**Closed by gaul** 2024-02-20 02:24 UTC
