### ISSUE TITLE
how to put authentication mechanism to access s3Proxy?

### ISSUE THREAD

**Issue by oberai07** [gaul/s3proxy#582] opened 2023-12-26 12:50 UTC
Currently, we don't have any authentication mechanism to access the s3proxy or APIs. We need a way to set the authentication for s3proxy. How we can design/implement the same?

**Comment by gaul** [comment] 2023-12-27 02:37
Could you be more specific about your use case?  Are you embedding S3Proxy into another Java app?  If so you should look at `S3ProxyHandler.setBlobStoreLocator` which allows dynamic authentication.

**Comment by oberai07** [comment] 2023-12-27 08:23
No, we are not using with Java app. We are using it to store the DB backups in the k8s(Kubernetes) environment and we don't want anybody to access the buckets and objects(Db backups) without authentication.

**Comment by gaul** [comment] 2023-12-27 10:09
If you set `s3proxy.authorization` to `aws-v4` then S3Proxy will operate as AWS does, enforcing the correct `s3proxy.identity` and `s3proxy.credential` values.  Currently you set it to `none` which ignores authorization entirely.

**Comment by oberai07** [comment] 2023-12-27 10:18
If I set` s3proxy.authorization `to `aws-v4 ` then it will throw me an access denied error. Please refer my another issue that I opened with you guys already. Could you please let me know, how we can enforce the correct `s3porxy.identity `and `s3proxy. credential` and what should be the values of both keys? 

https://github.com/gaul/s3proxy/issues/581

**Comment by gaul** [comment] 2023-12-27 11:18
Duplicate of #581.

**Closed by gaul** 2023-12-27 11:18 UTC
